
export default {
    API: {
        PUSH_QUEUE_ITEM: 'PUSH_QUEUE_ITEM',
        POP_QUEUE_ITEM: 'POP_QUEUE_ITEM'
    },
    Auth: {
        LOGOUT: 'LOGOUT',
        LOGIN: 'LOGIN'
    },
    Article: {
        EMPTY_ARTICLES: 'EMPTY_ARTICLES',
        READ_ARTICLES: 'READ_ARTICLES',
        WRITE_ARTICLE: 'WRITE_ARTICLE',
        MODIFY_ARTICLE: 'MODIFY_ARTICLE',
        DELETE_ARTICLE: 'DELETE_ARTICLE',
        CHANGED_ARTICLE: 'CHANGED_ARTICLE'
    }
}
